// Snapshot of koussay.online, 2026-10-04. Edit here; the site reads only this repo (D-11).
const project = {
  slug: "pixenhouse",
  name: "PIXENHOUSE",
  updated: "2026-09-14T11:45:00.000Z",
  type: "Brand & Web",
  kind: null,
  client: null,
  industry: null,
  location: null,
  year: "2026",
  role: null,
  services: [],
  status: null,
  liveUrl: "https://www.pixenhouse.ae",
  summary:
    "Brand and website for a Dubai production studio. New identity, their green kept, built in Framer so a first visit explains who they are.",
  overview:
    "PIXENHOUSE makes commercials, brand films, social content, and influencer work. I designed the logo, colour, type, and guidelines from scratch, then designed and built the full site in Framer. The page answers questions as you scroll: who they are, who they work with, what they do, how they work, their network, what people say, then what people ask. Green is the one thing I kept.",
  challenge:
    "The old brand was basic and the site was broken, so the studio was hard to read. They needed a fresh identity without losing the green people already knew, and a site that could stand in for a pitch. 11 days, 4 to 15 February 2026.",
  approach: null,
  outcome:
    "The studio can explain itself in one scroll. Since launch they signed two large clients on one-year contracts from the website.",
  tools: ["Framer", "Adobe illustrator", "Adobe Photoshop"],
  testimonial: null,
  identity: null,
  gallery: [
    {
      media: "brand-guideline-p01",
      alt: "PIXENHOUSE — page 1 of 29. Brand & Web by Koussay Zayani.",
      kind: "identity",
      caption: null,
    },
    {
      media: "brand-guideline-p02",
      alt: "PIXENHOUSE — page 2 of 29. Brand & Web by Koussay Zayani.",
      kind: "identity",
      caption: null,
    },
    {
      media: "brand-guideline-p03",
      alt: "PIXENHOUSE — page 3 of 29. Brand & Web by Koussay Zayani.",
      kind: "identity",
      caption: null,
    },
    {
      media: "brand-guideline-p04",
      alt: "PIXENHOUSE — page 4 of 29. Brand & Web by Koussay Zayani.",
      kind: "identity",
      caption: null,
    },
    {
      media: "brand-guideline-p05",
      alt: "PIXENHOUSE — page 5 of 29. Brand & Web by Koussay Zayani.",
      kind: "identity",
      caption: null,
    },
    {
      media: "brand-guideline-p06",
      alt: "PIXENHOUSE — page 6 of 29. Brand & Web by Koussay Zayani.",
      kind: "identity",
      caption: null,
    },
    {
      media: "brand-guideline-p07",
      alt: "PIXENHOUSE — page 7 of 29. Brand & Web by Koussay Zayani.",
      kind: "identity",
      caption: null,
    },
    {
      media: "brand-guideline-p08",
      alt: "PIXENHOUSE — page 8 of 29. Brand & Web by Koussay Zayani.",
      kind: "identity",
      caption: null,
    },
    {
      media: "brand-guideline-p09",
      alt: "PIXENHOUSE — page 9 of 29. Brand & Web by Koussay Zayani.",
      kind: "identity",
      caption: null,
    },
    {
      media: "brand-guideline-p10",
      alt: "PIXENHOUSE — page 10 of 29. Brand & Web by Koussay Zayani.",
      kind: "identity",
      caption: null,
    },
    {
      media: "brand-guideline-p11",
      alt: "PIXENHOUSE — page 11 of 29. Brand & Web by Koussay Zayani.",
      kind: "identity",
      caption: null,
    },
    {
      media: "brand-guideline-p12",
      alt: "PIXENHOUSE — page 12 of 29. Brand & Web by Koussay Zayani.",
      kind: "identity",
      caption: null,
    },
    {
      media: "brand-guideline-p13",
      alt: "PIXENHOUSE — page 13 of 29. Brand & Web by Koussay Zayani.",
      kind: "identity",
      caption: null,
    },
    {
      media: "brand-guideline-p14",
      alt: "PIXENHOUSE — page 14 of 29. Brand & Web by Koussay Zayani.",
      kind: "identity",
      caption: null,
    },
    {
      media: "brand-guideline-p15",
      alt: "PIXENHOUSE — page 15 of 29. Brand & Web by Koussay Zayani.",
      kind: "identity",
      caption: null,
    },
    {
      media: "brand-guideline-p16",
      alt: "PIXENHOUSE — page 16 of 29. Brand & Web by Koussay Zayani.",
      kind: "identity",
      caption: null,
    },
    {
      media: "brand-guideline-p17",
      alt: "PIXENHOUSE — page 17 of 29. Brand & Web by Koussay Zayani.",
      kind: "identity",
      caption: null,
    },
    {
      media: "brand-guideline-p18",
      alt: "PIXENHOUSE — page 18 of 29. Brand & Web by Koussay Zayani.",
      kind: "identity",
      caption: null,
    },
    {
      media: "brand-guideline-p19",
      alt: "PIXENHOUSE — page 19 of 29. Brand & Web by Koussay Zayani.",
      kind: "identity",
      caption: null,
    },
    {
      media: "brand-guideline-p20",
      alt: "PIXENHOUSE — page 20 of 29. Brand & Web by Koussay Zayani.",
      kind: "identity",
      caption: null,
    },
    {
      media: "brand-guideline-p21",
      alt: "PIXENHOUSE — page 21 of 29. Brand & Web by Koussay Zayani.",
      kind: "identity",
      caption: null,
    },
    {
      media: "brand-guideline-p22",
      alt: "PIXENHOUSE — page 22 of 29. Brand & Web by Koussay Zayani.",
      kind: "identity",
      caption: null,
    },
    {
      media: "brand-guideline-p23",
      alt: "PIXENHOUSE — page 23 of 29. Brand & Web by Koussay Zayani.",
      kind: "identity",
      caption: null,
    },
    {
      media: "brand-guideline-p24",
      alt: "PIXENHOUSE — page 24 of 29. Brand & Web by Koussay Zayani.",
      kind: "identity",
      caption: null,
    },
    {
      media: "brand-guideline-p25",
      alt: "PIXENHOUSE — page 25 of 29. Brand & Web by Koussay Zayani.",
      kind: "identity",
      caption: null,
    },
    {
      media: "brand-guideline-p26",
      alt: "PIXENHOUSE — page 26 of 29. Brand & Web by Koussay Zayani.",
      kind: "identity",
      caption: null,
    },
    {
      media: "brand-guideline-p27",
      alt: "PIXENHOUSE — page 27 of 29. Brand & Web by Koussay Zayani.",
      kind: "identity",
      caption: null,
    },
    {
      media: "brand-guideline-p28",
      alt: "PIXENHOUSE — page 28 of 29. Brand & Web by Koussay Zayani.",
      kind: "identity",
      caption: null,
    },
    {
      media: "brand-guideline-p29",
      alt: "PIXENHOUSE — page 29 of 29. Brand & Web by Koussay Zayani.",
      kind: "identity",
      caption: null,
    },
  ],
};

export default project;
